### ISSUE TITLE
Is there any xamarin implementation

### ISSUE THREAD

**Issue by tony683** [mono/monotorrent#178] opened 2019-11-14 02:04 UTC
As this protable library ,just wanted to ask ,it there any xamarin implementation.
I was trying to implement this in Xamarin,but it seems some methods are missing

**Comment by alanmcgovern** [comment] 2019-11-14 08:04
This is a .NET standard 2.0 library, so all you need to do is reference the nuget from your xamarin project and it'll just work. 

You can also compile from source if you have an IDE which is new enough to support the c# 8.0 language syntax. 

What issue are you having?

**Comment by tony683** [comment] 2019-11-17 03:57
I already did that,but downloads are not getting started.Firewall is not an issue.
I downloaded bittorrent,was able to dowload torrents...Downloada are getting started,
but when i tried through this library ,downloads are not getting started

**Comment by alanmcgovern** [comment] 2019-11-17 09:30
Can you share a copy of a torrent that doesn't work?

**Comment by tony683** [comment] 2019-11-18 02:19
here is the project that i am using-
https://github.com/nikkonrom/outflow

this one is in wpf,but i was able to convert it in xamarin.forms.
but the problem is downloads are not starting.
This is the torrent file i want to download-
https://drive.google.com/open?id=1SBknMHLaEC6lHO8EndA2TQLz_GnPr_4D

**Comment by alanmcgovern** [comment] 2019-11-18 17:25
What program created that torrent? It appears to be invalid for at least 2 separate reasons.

1) The keys in the BEncodedDictionary are not alphabetical, as the must be according to the spec.
2) Even if you attempt to load the torrent with strict decoding disabled [0], the 'Comment' is malforme. When parsed the value is `Torrent downloaded from / ( former yts.am/yts.ag )10:created by`. As you can see it the length of the comment is incorrect and it results in the *next* key being read in as part of the comment value.

Transmission also cannot open the torrent, neither can https://chocobo1.github.io/bencode_online/. 

[0]
```
                        var dict = (BEncodedDictionary) BEncodedValue.Decode (new RawReader (File.OpenRead (file), false));
                        torrent = Torrent.Load(dict);
```

**Comment by tony683** [comment] 2019-11-19 09:01
I downloaded that torrent file from internet
https://yst.am/movie/the-dark-knight-2008

I saw decoding through codes,and I agree with you,but still if a torrent can be downloaded through utorrent , bittorrent etc like other torrent clients,then why this library cannot .

**Comment by OneFingerCodingWarrior** [comment] 2019-11-19 09:13
> I saw decoding through codes,and I agree with you,but still if a torrent can be downloaded through utorrent , bittorrent etc like other torrent clients,then why this library cannot .

because the library needs contributors like you to make it perfect!

**Comment by alanmcgovern** [comment] 2019-11-19 10:31
> I saw decoding through codes,and I agree with you,but still if a torrent can be downloaded through utorrent , bittorrent etc like other torrent clients,then why this library cannot .

The torrent you uploaded *cannot* be downloaded by any torrent client as it is corrupt. Can you double check you uploaded the correct file?

<img width="647" alt="Screenshot 2019-11-19 at 10 30 44" src="https://user-images.githubusercontent.com/264396/69139036-a878bf80-0ab7-11ea-9854-51eb2345f641.png">

**Comment by alanmcgovern** [comment] 2019-11-19 15:02
Actually I think I'll go ahead and close this issue as the problem stated in the title of the issue is not what's being discussed now. 

If there is a problem with missing methods, or things not being compatible with Xamarin.iOS, Xamarin.Android or Xamarin.Mac, please reopen this issue and pass on any relevant information. As this is a .NET Standard 2 compatible library I would not anticipate any issues.

If you have issues with specific valid torrents, or just issues in general, please open a new issue with a description of the problem and I'll see what I can do. 

Thanks!

**Closed by alanmcgovern** 2019-11-19 15:02 UTC
