### ISSUE TITLE
Error when using Torrent.Load

### ISSUE THREAD

**Issue by ChillSheep** [mono/monotorrent#199] opened 2019-12-15 18:50 UTC
The type ‘System.Object’ is defined in an assembly that is not referenced. You must add a reference to assembly ‘netstandard, Version=2.0.0.0, Culture=neutral

Torrent torrent = Torrent.Load("C:\\1.torrent");

**Comment by alanmcgovern** [comment] 2019-12-15 21:05
If this is a compilation error in your project, make sure your project is targeting .NET 4.7.2 or higher.

If that doesn't fix it then please share a copy of the csproj with the error.

**Comment by HelloWindowsPhone** [comment] 2019-12-16 02:34
A clean and rebuild solution should fix it

**Comment by alanmcgovern** [comment] 2019-12-17 14:34
I'll close this as it's not a monotorrent related issue. This looks like a fairly standard .NET compilation issue caused by mismatched frameworks.

As long as your chosen framework version is compatible with .NETStandard 2.0 or greater then everything should work fine.

**Closed by alanmcgovern** 2019-12-17 14:34 UTC
