### ISSUE TITLE
(UWP) System.InvalidOperationException: Cannot call Set on a null context

### ISSUE THREAD

**Issue by uponatime2019** [mono/monotorrent#202] opened 2019-12-16 17:44 UTC
[TestMonoTorrentUWP.zip](https://github.com/mono/monotorrent/files/3969404/TestMonoTorrentUWP.zip)

I'm implement MonoTorrent in UWP project. It's work perfect in Debug mode, but in Release mode (only happen on Release) (submit to Store), an UnhandledException happen with this error message
You can see in attached sample UWP project
```
System.InvalidOperationException: Cannot call Set on a null context
   at System.Threading.ExecutionContext.Run(ExecutionContext, ContextCallback, Object) + 0x3e
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.CallMoveNext() + 0x7f
   at System.Action.Invoke() + 0x25
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action, Boolean, Task&) + 0x43
```

**Comment by alanmcgovern** [comment] 2019-12-16 21:42
https://github.com/dotnet/corert/issues/5603

It could be a bug in the runtime. If you can easily reproduce the issue, could you comment out the pieces of the code which call ExecutionContext.Suppress (there are a few) and see if that solves the problem on UWP?

**Comment by uponatime2019** [comment] 2019-12-17 02:13
![image](https://user-images.githubusercontent.com/15900671/70958964-64c0a800-20ad-11ea-9fdc-df2ad12a1cf5.png)
Lines that cause bugs from MessageLoop.cs
209-211
245-247
249-251

**Comment by alanmcgovern** [comment] 2019-12-17 10:28
If these lines are commented out then the Dht engine will be broken as it looks like all the change does is make it so that messages are never marked as sent or timed out.

The bug i linked has some additional information which may help you. There's a way to get more logging from the exception 


Also, the change I suggested may  solve the problem safely. Did you try that to see if it resolved the issue?

**Comment by uponatime2019** [comment] 2019-12-17 15:20
I just comment out these lines as your sugggest and problem gone on Release mode UWP
![image](https://user-images.githubusercontent.com/15900671/71008530-58733400-211b-11ea-9f1d-5114e9cf86d1.png)

**Comment by alanmcgovern** [comment] 2019-12-17 18:03
I'll merge similar changes into the library so it works out of box on UWP

**Closed** 2019-12-19 10:23 UTC

**Comment by uponatime2019** [comment] 2020-01-23 10:44
Hi, did this issue fixed on latest nuget release?

**Comment by alanmcgovern** [comment] 2020-01-30 08:05
Sorry - this change is in 1.0.14!

**Comment by alanmcgovern** [comment] 2020-01-30 08:05
@uponatime2019  see the comment above this one :)
