### ISSUE TITLE
Torrent not loading

### ISSUE THREAD

**Issue by Crazyx001** [mono/monotorrent#111] opened 2019-08-14 10:57 UTC
Please help, why SampleClient can not download my torrent file, what could be the reason?

**Comment by alanmcgovern** [comment] 2019-08-14 13:16
If you have a recent build then it was probably https://github.com/mono/monotorrent/commit/b777dcb229f8e1ee424742cfe42ffedefb5c5206

**Comment by alanmcgovern** [comment] 2019-08-14 17:45
If the latest revision resolves the problem you were having (the regression from a few commits ago) then please close the issue. Otherwise do share as much information as you can to help me figure out what's going wrong. Thanks

**Comment by alanmcgovern** [comment] 2019-08-16 06:38
If you're still getting issue that are not resolved by using a newer build, please reopen this. Based on the timing of your report the problem is most likely the short-lived regression which was addressed already. Thanks !

**Closed by alanmcgovern** 2019-08-16 06:38 UTC

**Comment by Crazyx001** [comment] 2019-08-21 14:36
Hello. Sorry for such a long answer, because I was away on business. Unfortunately your advice didn’t help me and yes, I am using the latest library build.
