### ISSUE TITLE
Seeding not work

### ISSUE THREAD

**Issue by justscribe** [mono/monotorrent#195] opened 2019-12-02 15:54 UTC
Hi,

I have a lot of clients that uses MonoTorrent, and when they downloaded all the files (or a part with DoNotDownload), they start to seed, but other clients can't download files from clients that seeding with MonoTorrent, only if another custom client seeding (qBitTorrent, etc.).

**Comment by justscribe** [comment] 2019-12-02 16:00
![image](https://user-images.githubusercontent.com/8200485/69974159-5743e380-152d-11ea-9876-57c7a19f3e8c.png)
![image](https://user-images.githubusercontent.com/8200485/69974262-91ad8080-152d-11ea-974c-eaf682c94fc0.png)

**Comment by alanmcgovern** [comment] 2019-12-02 16:02
Hrm... that's quite odd so let me do some testing locally! I'll assume this is specific to the partial-seeding code so I'll test that setup.

**Comment by justscribe** [comment] 2019-12-02 16:05
In the logs many errors about:
ConnectionAttemptFailed, ConnectionUri - ipv4://x.x.x.x:1000/, Reason - Unreachable

**Comment by justscribe** [comment] 2019-12-02 16:22
But, I can somehow download by another client from MonoTorrent seeding clients.
As you see, qBitTorrent uses another port (not my, hardcoded in the client), so Idk how to find a workaround. Seems it finds it by PeerExchange or LocalPeerDiscovery.
![image](https://user-images.githubusercontent.com/8200485/69975503-02559c80-1530-11ea-9a39-ae612ddccefc.png)

**Comment by alanmcgovern** [comment] 2019-12-02 17:15
It's not immediately obvious what's going on in your screenshots.

It looks like there are two different torrents being used, and the client which uploaded about 83 gigabytes was seeding torrent 43, but the rest of the ones you highlighted were seeding torrent 41. If that's correct then I think that's the explanation for the different amounts of data.

If that's not correct, could you give me a detailed description of exactly what you have set up?

Finally, in your second screenshot it looks like all the active connections to monotorrent clients were made by MonoTorrent. i.e. MonoTorrent was able to connect to qBitTorrent, but qBitTorrent was not able to connect to MonoTorrent. If that's the case then it's possible you have misconfigured the listening address somehow and MonoTorrent is not actually listening on port 1000. Can you share a copy of the code where you configure the engine and its listening port?

**Comment by alanmcgovern** [comment] 2019-12-02 17:27
```
In the logs many errors about:
ConnectionAttemptFailed, ConnectionUri - ipv4://x.x.x.x:1000/, Reason - Unreachable
```
For every computer which *should* be listening on port 1000, can you run `netstat -a -b` in an elevated command prompt and make sure it is actually listening on TCP port 1000?

If it is listening, then can you run `telnet <ip> <port>` and see a second machine is able to connect to it?

For example if you have monotorrent listening on port 1000 on machine 192.168.0.5 then you can run:
`telnet 192.168.0.5 1234` to see it time out and fail, then `telnet 192.168.0.5 1000` to see it connect. When it connects the screen will be empty. If you keep typing and pressing enter you will eventually send enough data for part of the encrypted handshake process to send data to you. It will show up as random junk like this:
<img width="1355" alt="Screenshot 2019-12-02 at 17 26 53" src="https://user-images.githubusercontent.com/264396/69980839-f4504d80-1528-11ea-86b7-2d55e3415147.png">

Note: if encrypted connections are not enabled then you'll probably just get disconnected as soon as you send at least 68 bytes of junk.

**Comment by alanmcgovern** [comment] 2019-12-02 17:29
Also, telnet is not installed on windows 10 by default, so you may need to manually install it ( https://www.technipages.com/windows-10-enable-telnet )

**Comment by justscribe** [comment] 2019-12-02 17:30
Settings for Engine:
                    ```
_engineSettings = new EngineSettings {
                    AllowedEncryption = EncryptionTypes.All,
                    ListenPort = _port,
                    SavePath = AppConsts.cacheDir,
                    MaximumConnections = 600,
                    MaximumOpenFiles = 10,
                    MaximumHalfOpenConnections = 100,
                    PreferEncryption = false,
                    MaximumUploadSpeed = int.MaxValue,
                    MaximumDownloadSpeed = int.MaxValue,
                };
                _engine = new ClientEngine(_engineSettings, new DiskWriter(10));
```

**Comment by justscribe** [comment] 2019-12-02 17:38
About the torrents, yes, they are different. But when the qBitTorrent was enabled for torrent 41, all clients has been downloading from it.
We have now 2 torrents, in normal situation we have 2 qBitTorrent seeds, and other MonoTorrent clients, that can download/seed. So the problem arrived when we have a lot MonoTorrent seeds and no qBitTorrent seed, and in this situation download doesn't start.

**Comment by justscribe** [comment] 2019-12-02 18:15
So, every client got has similar situation:
![image](https://user-images.githubusercontent.com/8200485/69983903-7ac45980-1540-11ea-8c62-d382aa0d3e8f.png)

**Comment by alanmcgovern** [comment] 2019-12-02 18:26
can you show the completion status of each connected peer, the value for AmInterested and also IsChoking?

**Comment by justscribe** [comment] 2019-12-02 18:51
Here the logs, spamming message:
![image](https://user-images.githubusercontent.com/8200485/69986181-849c8b80-1545-11ea-8db7-f4b868a36b14.png)

**Comment by justscribe** [comment] 2019-12-02 19:24
Can it be, that router blocks direct connections?
I've did a little test, with my desktop client seed and notebook client with 4G connection, so I've started downloading from through port 1000, without issues.
But how It can be, that from 30 seeds, with allowed firewall, no one can seed, except me... and qBitTorrent.

**Comment by alanmcgovern** [comment] 2019-12-02 20:35
Can you call `GetPeersAsync` every few seconds like this https://github.com/mono/monotorrent/blob/master/src/SampleClient/main.cs#L221-L226 . The bits of information I need are `peer.AmInterested`, `peer.IsInterested`, `peer.AmChoking`, `peer.IsChoking`, `p.BitField.TrueCount` and `p.BitField.Clone ().And (manager.Bitfield).TrueCount` . With that I should be able to do a reasonable double check to see if the various flags look correct, and whether or not things should be being requested.

If you can also log `manager.PieceManager.CurrentRequestCountAsync()` then we can double check pieces are actually being requested once a peer is interesting and has unchoked the local client.

The interested/choking status changes over time so a snapshot of the data when the peer initially connects will only show the default values, it won't show us if any peer is unchoked, or becomes interesting, later on.

Sorry for all the questions, but this kind of problem is very hard to diagnose remotely when it can't be reproduced :(

**Comment by alanmcgovern** [comment] 2019-12-02 20:38
Actually i have an idea, give me a little bit of time to check before you go doing any more work!

**Comment by alanmcgovern** [comment] 2019-12-02 20:51
No, that wasn't it. If you can provide the information i requested I might be able to make some headway on the problem!

**Comment by justscribe** [comment] 2019-12-03 06:45
So, I can say, that seeding is working, but not by the way I've expected:
![image](https://user-images.githubusercontent.com/8200485/70025475-dd037580-15a5-11ea-8070-7ea3d2cd7be4.png)
As you see, the client is using different remote port for download (all, seed and client is Mono).
In our application we're using a short timeout, to start the torrent (30 sec), if no download starts, we're going to use HTTP download. I've did a small test, and the time when client finally finds seed is about 4 minutes.
The question is, can we somehow rapid that process?

**Comment by alanmcgovern** [comment] 2019-12-03 11:31
When a client cannot connect to a remote peer and shows it as 'Unreachable', can you run the telnet test ( https://github.com/mono/monotorrent/issues/195#issuecomment-560495848 ) on the 'unreachable' ip/port to see if it is also unreachable to telnet?

When you have a client with multiple established connections and that client is not downloading data, can you gather this information ( https://github.com/mono/monotorrent/issues/195#issuecomment-560569548 ). 

If it takes a long time to connect to peers, can you add logging to the `TorrentManager.PeersFound` event. If you log the object type we will know which PeersAddedEventArgs subclass it is (DhtPeersAdded, LocalPeersAdded,  PeerExchangePeersAdded, TrackerPeersAdded) and you can log the ip/port for each peer we can check it later to verify it is correct.

I don't think there's a *slowness* problem, i think monotorrent is attempting to connect to people very quickly but that attempt is failing, for unknown reasons. You can see that occurring in the logs - there are three connection attempts right after it enters 'Downloading' mode and they all failed. I assume they should not be failing.

**Comment by justscribe** [comment] 2019-12-03 13:38
Unfortunately I can't do like that, I have not access to those machines(
I only have access to the tracker and client deploy system.
Now some additional people start to seed, so I can download mostly immediatly (on PeerExchangePeersAdded it started downloading):
![image](https://user-images.githubusercontent.com/8200485/70055693-c0396300-15e2-11ea-8130-38a29baedc58.png)

**Comment by alanmcgovern** [comment] 2019-12-03 15:12
```
Unfortunately I can't do like that, I have not access to those machines
```
You can do the telnet check from any machine. If *any* machine is able to connect to an ip/port that is marked by MonoTorrent as 'unreachable' then it would indicate a bug in MonoTorrent. Otherwise the simplest explanation is probably right - those machines are behind a firewall/NAT and are not accessible as the port hasn't been opened/forwarded successfully. In this scenario the only way that peer will connect to another peer would be if it queries the tracker and receives a new list of peers and those peers are publicly reachable.

If some peers are running on linux machines then any port number between 1 and 1024 requires root privileges. That means the client would fail to bind to the port, and so would be incapable of receiving incoming connections. The solution here would be to use port 1025 or higher.

```
I only have access to the tracker and client deploy system.
```
Well, there is one interesting thing you can do if you control the tracker. If the tracker is private and you know that the number of active peers is not going to be in the 10,000s or higher, you should be able to do a connectivity check from the tracker for every peer when they first announce. All you need to do is get the tracker to connect to the original peer using the `ip` and `port` contained within the announce. If the announce request does not contain an `ip` then the `ip` address from the HTTP request should be used. i.e. if the http request was received from 189.462.123.4 then that should be the IP address the tracker attempts to connect to. All you need to do is a `Socket.Connect` call. If that succeeds then they're reachable and you can close it immediately without sending any actual data.

Some trackers put a message in the [warning message](https://github.com/mono/monotorrent/blob/master/src/MonoTorrent/MonoTorrent.Client.Tracker/HTTPTracker.cs#L271-L273) parameter to warn clients that they are not publicly accessible.

For now I don't think there's anything that can be done on my side. In scenarios where machines are definitely publicly accessible, every client seems to connect as expected. They then download and share the expected data when doing either full or partial download. I have 4 machines and have tried running 1 client per machine, as well as multiple clients per machine. It's entirely possible there's an issue, but as I have to recreate the entire scenario without any access to your problematic setup it's possible I missed something.

I'll need some more data (like i previously outlined) before we can make the determination that there's a bug in monotorrent :(

**Comment by justscribe** [comment] 2019-12-03 15:54
1. Sorry, I thought you mean I need to run it from seed machine. The answer is no, I can't connect via telnet (Connecting To x.x.x.x...Could not open connection to the host, on port 1000: Connect failed) if MonoTtorrent marks it as 'unreachable'.
2. Tracker is on php=)

**Comment by alanmcgovern** [comment] 2019-12-03 17:28
Ah no worries!

1. It looks like my assumption about connectivity was correct. If you can't telnet into that ip/port then monotorrent also won't be able to connect. That means the only way those peers will ever connect to anyone would be if they contact the tracker and that tracker returns at least one peer which is publicly accessible. Once at least one connection is established then PeerExchange will (hopefully!) allow more peers to be shared without needing to wait for a second tracker announce.

2. At the moment we're confident enough that the issue is that some peers are just not publicly accessible as you ran the telnet test. As such we don't really need to instrument the tracker to try and run that check for every peer :)

Next steps:
If you find a lot of monotorrent peers are sitting around not downloading, it could be because they have not yet been able to connect to a peer which has data. The second set of logging (about active peers) would answer that, but it would require instrumenting the actual client to enhance the logging.

You could infer this by correlating the peers each client connects to with that peers status according to their last announce. For example, if my client connects to remote peer 1.2.3.4 on port 5000, then i can check with the tracker to see if the peer at 1.2.3.4:5000 has sent `0` for the amount of bytes left. If they have then they're a seeder. If you're using partial downloading then that peer is a partial seeder if the amount of bytes left is equal to the amount of data they are choosing to not download. It's a tricky set of diagnostics to work out though. Instrumenting the client would be easier and more reliable.

If you can find a scenario where two clients connect, and one client has data the second client needs, and the second client *does not* request it, then do let me know. Nothing is impossible but i do think it is unlikely for this to be a common issue.

**Comment by justscribe** [comment] 2019-12-04 05:46
I the end I understood, that they just can't seed, by Mono or other clients.
On my machine that ports simply opened by router config (by port forwarding, because of DHCP), on other machines I don't think so.
Thank you for help, now I have better understanding about how it works.

**Closed** 2019-12-04 05:46 UTC

**Comment by alanmcgovern** [comment] 2019-12-04 20:39
If you need a solution for UPNP or NAT-PMP port forwarding, check out https://github.com/mono/mono.nat . It's another project of mine
