### ISSUE TITLE
Reusable tasks error.

### ISSUE THREAD

**Issue by justscribe** [mono/monotorrent#189] opened 2019-11-27 05:45 UTC
On some machines getting this error, on some all is good.

```
ReusableTasks.InvalidTaskReuseException: HasValueSentinel - Should not be invoked.
   в System.Runtime.CompilerServices.ResultHolder.<>c.<.cctor>b__4_2()
   в System.Runtime.CompilerServices.ResultHolder`1.TryInvoke(Action callback)
   в System.Runtime.CompilerServices.ResultHolder`1.TrySetExceptionOrResult(Exception exception, T result)
   в System.Runtime.CompilerServices.ResultHolder`1.SetResult(T result)
   в MonoTorrent.Client.Connections.SocketConnection.HandleOperationCompleted(Object sender, SocketAsyncEventArgs e)
   в System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   в System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
   в System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   в System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```

**Comment by OneFingerCodingWarrior** [comment] 2019-11-27 05:53
do you update to the latest ReusableTasks 1.0.5 ?

**Comment by justscribe** [comment] 2019-11-27 05:56
Yes, 1.0.5 installed via Nuget.

**Comment by OneFingerCodingWarrior** [comment] 2019-11-27 06:01
well, this exception is throwed quiet often before 1.0.5, but I test the 1.0.5 the exception is no longed throwed.
I has only one computer to test which has amd 8 cores cpu

**Comment by alanmcgovern** [comment] 2019-11-28 11:16
I've been doing some more thorough stress testing and while I can't trigger a problem anymore I do think there's a subtle race condition. 

I believe it's possible for IsComplete to be invoked after the HasValue flag has been set, but before the continuation field has been updated. This can cause the task to complete synchronously, which means we could complete synchronously *and* asynchronously.

I never liked having a HasValue flag in addition to the continuation field, so I think I'll go ahead and simplify that. My understanding of this ill-documented extension point is a bit better now which helps. 

If only there was some thorough documentation covering the exact semantics expected by the runtime :p 

I'll issue a pre-release update on NuGet for ReusableTask and then ask you to update to that pre-release to see if it solves the problem! If it does I'll promote the release to stable.

**Comment by alanmcgovern** [comment] 2019-11-28 12:12
@justscribe Can you manually reference version `1.0.6-beta` of ReusableTasks in your project to force it to upgrade, and then let me know if the problem goes away. After some serious thinking I am pretty certain the fix in 1.0.5 was incomplete, and the second part added in 1.0.6-beta will fix this once and for all.

https://www.nuget.org/packages/ReusableTasks/1.0.6-beta

**Comment by alanmcgovern** [comment] 2019-11-28 12:40
Alternatively just reference the MonoTorrent `1.0.9-beta`  nuget package, or compile from here: https://github.com/mono/monotorrent/tree/monotorrent-1.0-beta . The only difference is that the minimum required ReusableTasks version was increased to 1.0.6-beta instead of 1.0.5.

Do let me know how you get on!

**Comment by justscribe** [comment] 2019-11-28 12:42
I've done checkout to previous version, that was without Reusable tasks for now.

**Comment by alanmcgovern** [comment] 2019-11-28 13:02
I believe a monotorrent version using ReusableTasks `1.0.0` -> `1.0.2` should also be reliable :)

However do use whatever keeps you unblocked!

**Comment by justscribe** [comment] 2019-11-28 19:21
Maybe that info will help, this issue caused when one man tried to download torrent on it's own machine, one torrent client is seeding, and monotorrent module is downloading, so the speed was very high.
In some point it drops without any error, in some cases was erros like (sorry for obfuscated methods):
```
System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   в System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   в EBEEOBJFPEGNOHIKDGCDNKHDGENAEPBBBECF.HFJDFIOJOLNADHPDOPBHDDLJGCANLEMKEKPA.A.AENHFKOMDOELCJJKFJCDPBLMPIFDPLMEIOHL(Object , Object , Int32 , Int32 )
   в EBEEOBJFPEGNOHIKDGCDNKHDGENAEPBBBECF.HFJDFIOJOLNADHPDOPBHDDLJGCANLEMKEKPA.A.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в EBEEOBJFPEGNOHIKDGCDNKHDGENAEPBBBECF.HFJDFIOJOLNADHPDOPBHDDLJGCANLEMKEKPA.A.AENHFKOMDOELCJJKFJCDPBLMPIFDPLMEIOHL(Object )
   в EBEEOBJFPEGNOHIKDGCDNKHDGENAEPBBBECF.HFJDFIOJOLNADHPDOPBHDDLJGCANLEMKEKPA.A.MoveNext()
```

**Comment by alanmcgovern** [comment] 2019-11-28 19:53
That looks like a different issue. 

The first issue reported is with ReusableTasks and normal socket connections. This stacktrace is related to HTTP connections (web seed or a tracker announce?) Which doesn't use ReusableTasks as far as I can tell. 

If the application is completely crashing then you should be able to get the stacktrace from the terminating exception if you attach to the AppDomain.CurrentDomain.UnhandledException event (or whatever it's called). That may shed more light on the problem.

**Comment by justscribe** [comment] 2019-11-28 19:58
UnhandledException event already handled with log writing, but it can't handle the crash... Strage...
You're confident that local seeding/downloading can't cause errors with ReusableTasks?

**Comment by alanmcgovern** [comment] 2019-11-28 20:10
It could, but without a stacktrace it's not possible to tell what's going on. I don't know how your logging works, but can you ensure you invoke Flush on the underlying stream before the event handler finishes running? That should ensure the data is on disk.

Is this running on Windows using the normal .net framework? If so you may be able to get more information by attaching the visual studio debugger to the application. If it's on mono you may be able to get more logging using MONO_LOG_LEVEL=info and MONO_LOG_TRACE=E:all. those environment variables should cause the full stacktrace of every thrown exception to be written to thr standard output stream

**Comment by alanmcgovern** [comment] 2019-12-02 09:06
I am confident enough that the latest changes in ReusableTasks 1.0.6 are, at the least, no less reliable than what 1.0.5 and do have a chance of fully resolving the issues which were reported with 1.0.4. I shipped those and bumped MonoTorrent to rely on 1.0.6. If there are still issues with the latest master builds, or MonoTorrent 1.0.9/ReusableTasks 1.0.6 then do let me know!

I'm going to close this for now, but please do reopen if it's not 100% stable.

**Closed by alanmcgovern** 2019-12-02 09:06 UTC

**Comment by samhocevar** [comment] 2019-12-02 19:42
I can confirm 1.0.6 fixed the issue for us. We have 180 clients running and we would get 10 crashes a day with 1.0.5, and everything looks fine now.

**Comment by justscribe** [comment] 2019-12-04 05:47
I'm agree, also no issues with 1.0.6.
